### ISSUE TITLE
watch out for __del__

### ISSUE THREAD

**Issue by tarekziade** [mozilla/PyVEP#4]
I've seen usage of **del** in one verifier. 

Two pitfalls: 
- you don't know when it's going to be called, it might happen _after_ the end of the execution,
- it might not get called if you have cyclic references (unless you use weakref)

I recommend doing the close() explicitely, or within a context manager

**Comment by rfk** [comment]
Yep, it would be much better to require consumers to call close() explicitly.  I added **del** to one of the new ones since that wasn't in the original usage contract of the Verifier class.

Unfortunately repoze.who plugins don't seem to have a clean teardown API, so I'm not sure how to arrange for it to be called.  Maybe there's something inside pyramid we can use?  Not sure.
