### ISSUE TITLE
generic vep.verify()

### ISSUE THREAD

**Issue by tarekziade** [mozilla/PyVEP#6]
Instead of having one function per verifier:

vep.verify_local
vep.verify_xxx
etc

why not having the verifier as an option for the verify() function (in a form of a string that points to the class) ?

that way, if I write my custom verifier we can do :

  vep.verify(..., verifier='tokenserver.verifier.Verifier')

(or even a cls= since I can instanciate it on my side)

**Comment by rfk** [comment]
I don't understand the advantage of this over instantiating the class and calling its verify() method::

```
tokenserver.verifier.Verifier().verify(...)
```

Got a particular use case in mind?

**Comment by tarekziade** [comment]
Being able to set the verifier through the configuration file

**Comment by rfk** [comment]
Sorry if I'm a bit dense this evening but I'm not sure I understand how this helps in that case.

By way of example, the VEPAuthPlugin class takes a verifier object as argument.  For the dev syncstorage server I have this in the configuration file::

```
[who.plugin.vepauth]
verifier = vep:RemoteVerifier
verifier_urlopen = urllib2:urlopen
```

The plugin loads this up to create a verifier object via the code at https://github.com/mozilla-services/repoze.who.plugins.vepauth/blob/master/repoze/who/plugins/vepauth/__init__.py#L373.  All the verification is then done by calling the verify() method on this object.

Something using mozscv could do the same by going::

```
verifier = load_and_register("verifier", config)
verifier.verify(assertion)
```

What would I gain in this scenario by using vep.verify() as another layer of indirection?

Don't get me wrong, I think that this change would clean some things up inside PyVEP itself.  But I'm not sure why you'd want to call it like that as a consumer of the library.  If you already have an instance of a Verifier class, why would you want to call something like vep.verify(assertion, cls=PowerHoseVerifier) instead of PowerHoseVerifier().verify(assertion)?

**Comment by tarekziade** [comment]
Ok sure I can do like this (that's how I am doing right now).

I am still not sure to see the point then to keep the verify_xxx function in PyVEP, but no big deal

**Comment by rfk** [comment]
Yes, you're right.  Thinking about it from this perspective, the verify_xxx functions don't make such sense.  There should be only two options:

```
* Want the simple defaults?  Use vep.verify().
* Want something specific?  Use a Verifier class.
```

I'll remove them in the next API revision.

**Comment by tarekziade** [comment]
sounds good, thanks!
